### PR TITLE
Add support for socketfile option

### PR DESCRIPTION
**Pull request by hengestone**
Hi there,

This adds support for connecting to a server using a unix socket instead of over TCP..

Thanks,
Conrad

### CODE REVIEW

**Comment by funny-falcon** [comment]
I don't like it. It is better to parse host, imho. For example, `if @host =~ r|^unix://(.*)| then connect_unix_socket end`

Please, thinl second time about, and change the patch.

**Comment by funny-falcon** [comment]
sub("thinl","think")

**Comment by funny-falcon** [comment]
Better. But why do you use different regexp?
My regexp allows both relative and absolute paths:

- `here.sock` => `unix://here.sock`
- `close/to.sock` => `unox://close/to.sock`
- `/far/away.sock` => `unix:///far/away.sock`

**Comment by hengestone** [comment]
2 reasons: 
- There's no such thing as a relative file uri, see 
https://tools.ietf.org/html/draft-ietf-appsawg-file-scheme-03
- Really!? You clearly have way too much time on your hands. Take the merge, don't take it, adapt it any way want. Enjoy the sunshine outside :-D

**Comment by funny-falcon** [comment]
I usually try to preserve original author of idea. That is why i've asked you to change change.

But if you really wish me to enjoy sunshine, I will close pull request, and just make similar changes by myself.

I'm also haughty so you are. Just be aware that it is bad property.

**Comment by hengestone** [comment]
Thanks for the merge :) If it were a bigger piece of code with some significant design decisions I would spend more time thinking about and debating it.
Thank you for your pedagogical style, and I apologize for sounding disrespectful.

I spent way too many decades staring at a screen, so not getting stuck in minutae and moving on to more important things is an original author idea worth preserving as well.

**Comment by funny-falcon** [comment]
I will merge it, and change:
`unix:file.sock` will be file with relative path `file.sock`
`unix:/var/file.sock` will be file with absolute path `/var/file.sock`
Note, it is not URI, so link to RFC is useless. It is not URI cause '127.0.0.1:11111' is not URI.

**Comment by funny-falcon** [comment]
BTW, why did you use `rindex` and `match`? why not just `=~` and `$1` ?

**Comment by hengestone** [comment]
Thanks for the merge and changes.

Since I use many languages on a daily basis I don't always remember the special syntax of each.
So in general I just end up with code that looks like C and not Perl :)

**Comment by funny-falcon** [comment]
I've realized, that my pattern a bit not fair :-( it will behave mistakenly if one wish to connect to host named "unix" :-D

Probably, I will change option to be an array for unix socket:

- `"unix:1234"` will be "host 'unix' and port '1234'"
- `[:unix, ”1234”]` will be "unix socket file named '1234’

API is very hard thing :-(

**Comment by hengestone** [comment]
Then you might as well use my original API that doesn't overload the host parameter ;-)

**Comment by funny-falcon** [comment]
No :-)

Just rename "host" to "connect point" in your mind, and you understand why.

If you wish, I'll rename it in a code.

**Pull request merged**
