### PR TITLE
Prevent occasional `uninitialized constant Tarantool16::Connection` error in tests

### PR DESCRIPTION
**Pull request by mindreframer**

### CODE REVIEW

**Comment by funny-falcon** [comment]
Which ruby versions you did check with?

**Comment by mindreframer** [comment]
```
$ ruby -v 
> ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin17]
```

**Comment by mindreframer** [comment]
@funny-falcon is there anything still missing in this PR to be accepted?

**Comment by funny-falcon** [comment]
Or, I forgot about. I wanted to test it in more ruby versions. Ok, since I didn't find time for, lets merge.

**Comment by mindreframer** [comment]
🎉 thank you!

**Pull request merged**
